name: CD to GHP v3

on: 
  push:
    branches:
      - dev
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Install dependencies & compile code
        run: |
          npm install
          npm run build
          ls -la

      - name: Build dist directory
        run: |
          mkdir dist
          mv .gitignore dist
          mv README.md dist
          mv assets dist
          mv dashboard.html dist
          mv index.html dist
          mv public dist
          mv style.css dist
          ls -la

      - name: Upload dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist
          retention-days: 1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: prod

      - name: Download dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ~/dist

      - name: Move dist into current directory
        run: |
          mv ~/dist ./
          ls -la

      # Configures git credentials before pushing up to target branch
      - name: Package new compiled code & deploy to target branch
        run: mv .git dist
      
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: prod
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  